name: AFL fmnist Non-iid sample2
on: workflow_dispatch

jobs:
  deploy:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run ansible playbook to add users
        run:  ls