name: AFL cifar10 noniid
on: workflow_dispatch

jobs:
  deploy:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run experiment
        run:  python main.py --federated_type afl --dataset cifar10 --data_dist from_csv --from_csv sample2
