name: FedAvg mnist iid
on: workflow_dispatch

jobs:
  deploy:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run experiment
        run:  python main.py --federated_type fedavg --dataset mnist --data_dist iid
